name: Release Management

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.2.3)'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Generate changelog
      id: changelog
      run: |
        # Simple changelog generation
        echo "## Changes" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        git log $(git describe --tags --abbrev=0 2>/dev/null || echo "HEAD")..HEAD --pretty=format:"- %s (%h)" >> CHANGELOG.md || echo "- Initial release" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        cat CHANGELOG.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Bump version and create tag
      if: github.event_name == 'workflow_dispatch'
      run: |
        npm version ${{ github.event.inputs.version }} --no-git-tag-version
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json
        VERSION=$(node -p "require('./package.json').version")
        git commit -m "chore: bump version to v${VERSION}"
        git tag "v${VERSION}"
        git push origin "v${VERSION}"
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name || format('v{0}', steps.version.outputs.version) }}
        release_name: Release ${{ github.ref_name || format('v{0}', steps.version.outputs.version) }}
        body: |
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Automated Features
          - ✅ Continuous Integration
          - ✅ Automated Dependency Updates  
          - ✅ Security Scanning
          - ✅ Code Quality Monitoring
          - ✅ Automated Testing
          
          This release was automatically created by the release workflow.
        draft: false
        prerelease: false

  notify-update:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - name: Update project status
      run: |
        echo "🎉 New release created! The project continues to evolve..."
        echo "Remember: Nobody Ever Wins Sh*T, but we keep improving anyway!"